### ISSUE TITLE
I am using Ubuntu 14.04 LTS, conda Python 2.7 : unable to install opencv

### ISSUE THREAD

**Issue by shravankumar147** [menpo/conda-opencv#1]
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > import cv2
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory

**Comment by remoteblue** [comment]
You may want to check your ./bashrc file to make sure your directory is OK. use 
$echo $PATH 
$echo $LD_LIBRARY_PATH 
to ensure the above environmental variables are fine.

**Comment by patricksnape** [comment]
It may be mis-linked. I would use the conda-forge OpenCV from now on.
